from debian

RUN apt-get update && apt-get install -y \
build-essential \
python3-dev git \
autoconf \
flex \
bison \
python3-pip \
virtualenv \
iverilog

RUN git clone https://github.com/chipsalliance/tools-cocotb-verilator-build build

WORKDIR build

RUN git submodule update --init
RUN make env/bin/verilator
RUN make env/bin/cocotb-config

RUN ln -s /usr/bin/python3 /usr/bin/python

